### PR TITLE
Add some hills to the waves page.

### LINKED ISSUE #143: Waves-n-Hills backgrounds
As an alternative to #31 Landscape Generator, we (by which I mean @toolness ) could combine waves and hills in pleasing but randomizable formations like this:
water-n-hills_BG_2
Or this:
water-n-hills_BG_1
You get the idea.
Trees, horizon, etc. can be added later, but for now these two elements - waves and hills, with perhaps a sky - would be sufficient to make nice animated backgrounds.

### PR DESCRIPTION
**Pull request by toolness**
This is an exploratory attempt to fix #143.  Right now I'm just adding hills to the waves page because it's easiest, but we can always separate the two out.

### CODE REVIEW

**Comment by toolness** [comment]
@ninapaley You're welcome to take a look at the netlify preview now but be warned that it is _extremely_ primitive at the moment, just some fixed-size hills interspersed at a fixed interval along the waves:

> image

Will make this look more like your mockups in #143 as I move forward!

**Comment by ninapaley** [comment]
That looks just like it's supposed to! Just needs some attractive distribution of the hills.

**Comment by toolness** [comment]
Ok, I've added a more random distribution but I'm not sure how attractive it is... do you have any suggestions for heuristics of whether a distribution is attractive?  Right now I'm putting a random smattering in, with more hills in the background and fewer in the foreground:

> image

The hills aren't varying much in their height though, hmm.

**Comment by ninapaley** [comment]
I think it's working quite well!

What may make it look better at this point is a gradual fading of the color lightness/saturation. The lowest/"closest" wave and hill should be full saturation. Then, as each layer recedes, it should get slightly lighter (more white - actually more whatever the "sky" color is, which is currently white), like 5%, so the topmost "farthest" layer is more faded. Is that do-able?

Being able to vary the stroke on the waves (while remaining proportional) would be good too.

**Comment by toolness** [comment]
Ooh yeah I should be able to fade the stuff in the distance to the sky color!

> Being able to vary the stroke on the waves (while remaining proportional) would be good too.

Do you mean varying the stroke as the waves recede into the distance?  Or do you mean adding a slider on the sidebar that allows the user to vary the stroke?  I assume you mean the former but just wanted to make sure.

**Comment by ninapaley** [comment]
I think the strokes are already scaling proportionally. I meant a slider enabling the user to scale the strokes, but keeping the proportional quality as is.

**Comment by webaissance** [comment]
This is cool. Might I suggest a way to hide the hills? Could be a checkbox - or perhaps a slider for number of hills which could start at 0...

**Comment by ninapaley** [comment]
Heck, there could also be a slider to raise and lower the hills from the waves. (Or better yet, to raise and lower the waves around the hills, like rising and falling tides or sea levels.) Water gets high enough/hills low enough, and all the hills disappear!

**Comment by toolness** [comment]
Ok cool!  Will definitely make all the hill stuff configurable.

With respect to the gradual fading of the colors, how does this kind of thing look?

> image

Here the furthest-away wave/hill is actually a 33% tint to white, because it was hard for me to tell the difference when it was only 5%.  My math and/or algorithm might be weird though.

**Comment by ninapaley** [comment]
@toolness That looks good!!

By 5% I meant adding tint in increments of 5%, so that "front" layer has 0%, next layer is 5% tinted, next layer is 10% tinted, next is 15% tinted, and so on. So in the illustration above, the furthestmost layer would be 40% white. However, if you can just say "make furthest layer x% tinted" and have it automatically create the create increments between the layers, that would be much better! Which is what I think you're doing because you're smarter than me. ;)

**Comment by toolness** [comment]
Okay, I've just added a "Hills" checkbox at the bottom of the sidebar on the waves page to enable/disable hills for now.  I'd rather have this code merged into the codebase sooner rather than later, and we can always add more fancy sliders to adjust hill density, height, et cetera later.

**Pull request merged**
