### PR TITLE
randHue color algorithm

### PR DESCRIPTION
**Pull request by mittimithai**
Added new color algo, cleaned up random-colors a bit

### CODE REVIEW

**Comment by ninapaley** [comment]
NICE! Thanks @mittimithai !

**Comment by ninapaley** [comment]
I really like this color combo that showed up in randhues just now:
Nice_colors

**Comment by ninapaley** [comment]
@toolness Can you review this and, if it passes muster, merge it with main?

**Comment by toolness** [comment]
Ooh cool! This is nice. Sorry it took me so long to get to this one, merging now!

**Review by toolness — APPROVED** [review]

**Pull request merged**
