### PR TITLE
Add a 'creature_frequency_multiplier' TOML property.

### LINKED ISSUE #191: Influence symbol frequency
Suppose I wanted some symbols - like the wings - to show up more often than they do. Because I have restricted the points wings can attach to, they show up less frequently than symbols that attach promiscuously to everything. Could there be a line I could add to the wings' TOMLs that would boost their frequency and increase their statistical likelihood of appearing in a creature, while still attaching only to certain points? @toolness

### PR DESCRIPTION
**Pull request by toolness**
Fixes #191.

Currently the implementation is fairly naive, in that a really large value for `creature_frequency_multiplier` will not be handled terribly efficiently, but we can optimize later if needed.

### CODE REVIEW

**Comment by toolness** [comment]
Hey @ninapaley, I've got a PR ready here for the `frequency_multiplier` idea we discussed in #191. Do you want to try it out by fiddling with the TOML files in this PR, before I commit it?

One thing I'm realizing is that I'm applying the `frequency_multiplier` not only to the symbols in the creature creator, but also to the symbols in the mandala generator.  Is that bad?  The argument you gave for `frequency_multiplier` seemed specific to wings in the creature system, so if you set a high value, it would not only increase its likelihood in being used in creatures, but also in mandalas, and for that matter in any other place in our code in the future where we randomly pick from our vocabulary.  That's how I implemented the feature at a conceptual level, at least, but re-reading the issue I'm not actually sure if that's what you wanted... oof.  Well anyhow let me know what you think.

**Comment by ninapaley** [comment]
Oh gosh! I was only thinking about it for the Creature, not the mandalas or anything else. Will check out the netlify link now!

**Comment by ninapaley** [comment]
It definitely works for the Creature! Wings are showing up all over the place now (and later I can tune the tomls to my satisfaction). But I say don't merge until/unless it can be overridden/ignored on the mandala and/or other possible applications.

**Comment by toolness** [comment]
Ok cool!

Hmm, since the frequency multiplier will only affect the creature thingy, maybe we should call it `creature_frequency_multiplier` or somesuch?

**Comment by ninapaley** [comment]
> Ok cool!
> 
> Hmm, since the frequency multiplier will only affect the creature thingy, maybe we should call it `creature_frequency_multiplier` or somesuch?

Fine with me! Just let me know.

**Comment by toolness** [comment]
Ok @ninapaley I renamed the property to `creature_frequency_multiplier` and made it only apply to creature stuff!  The changes you made to a few of the wing symbols are in there though, just FYI, so right now the creature creator uses wings a _lot_...  Feel free to change that on the `main` branch if you want.

**Comment by ninapaley** [comment]
Thanks! I just modified the wing tomls, with new multipliers of 5 or 10 max, so they shouldn't be as prevalent.

**Pull request merged**
